### ISSUE TITLE
Minecraft giving me "errors in currently selected datapacks..." when loading this mod.

### ISSUE THREAD

**Issue by YoBoySk33n** [CamoMano/Vanilla-Enhanced#5]
Here is a pastebin of the log when this error occurs.
https://pastebin.com/evnnJSHj

Edit:
Turns out it was turning off the generation of certain items/blocks in your mod (using mod menu) that was causing this issue.

How to recreate it:
- Run the following mods: Fabric API + Mod Menu + Vanilla Enhanced
- Run Minecraft
- Open "Mods" (that mod menu adds in the menu).
- Press on "Vanilla enhanced" image, then the configure button.
- Where you see "enable (item/block)" disable them. In my case I disabled Dark Granite, Marble, and Biomes.
- Create a new world. (Other Notable issue I just noticed, disabling the generation doesn't actually work (I least from what I'm seeing as I still see the blocks that I disabled)
- Close Minecraft.
- Run Minecraft again.
- Create or Open a world.
- Minecraft should give you a data pack error.

Other things to note:
- After the problem is now there, if you remove VE the error should go away, however when reapplying VE into the mod folder, the problem appears again (This is most likely because mod menu is saving the settings for the mod, including this problem)
- Re-enabling all the generating/spawn settings in mod menu does not fix the error appearing.

**Comment by CamoMano** [comment]
When changing values in the config the game needs to be restarted for all of the changes to apply. As for the issue, I will be releasing an update today that fixes this. This is happening because the game is trying to load tagged items that don't exist. So instead of disabling these items completely, they will just be prevented from generating. I should be able to disable them completely once 1.16.2 is released.

**Comment by CamoMano** [comment]
Fixed in 1.1.
